autorentool_rest:
    resource: "@AutorentoolCoreBundle/Controller/RestController.php"
    type:     annotation
    prefix: /api

autorentool_core:
    resource: "@AutorentoolCoreBundle/Controller/DefaultController.php"
    type:     annotation
    prefix: /

easy_admin:
    resource: "@EasyAdminBundle/Controller/"
    type: annotation
    prefix: /easyadmin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

## Optional
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group