# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
services:
    app.form.registration:
        class: AutorentoolUserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.security.authentication_handler:
        class: Autorentool\UserBundle\Handler\AuthenticationHandler
        public: false
        arguments:
            - "@router"
            - "@session"

    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: true

